### ISSUE TITLE
Allow typing into a cell without using the expression entry

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/Spreadsheet#45]
At the moment we can do only through that entry.

**Comment by aleksandar-stefanovic** [comment]
@ryonakano 

I'm having a difficult design decision here, since there are two ways for this to be implemented:

1. When something is typed while the cell is focused, focus moves to the expression entry (this is how it is currently implemented in #70)
2. When something is typed while the cell is focused, focus remains on the cell. The cell turns into a cell entry, an the expression entry and the cell entry become synchronized. (this is how it is in LibreOffice Calc, and presumably MS Office Excel)

Which one is better-fitting for this case?

**Comment by ryonakano** [comment]
@aleksandar-stefanovic I think the latter one (2.) would be even better, because the app works as people who are accustomed to use Calc or Excel expect, thus it would make them feel comfortable. 
However, if there are some difficulties when implementing, I personally think it's OK with the former one (1.).
